# Generated by Django 2.2 on 2021-11-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
