# Generated by Django 2.2 on 2021-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
