# Generated by Django 2.2 on 2021-11-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20211127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
